class MetaTagRewriter {
  constructor(tags) {
    this.tags = tags;
  }

  element(element) {
    const property = element.getAttribute("property") || element.getAttribute("name");
    
    if (property === "og:title" || property === "twitter:title") {
      element.setAttribute("content", this.tags.title);
    }
    if (property === "og:image" || property === "twitter:image") {
      element.setAttribute("content", this.tags.image);
    }
    if (property === "og:description" || property === "twitter:description") {
      element.setAttribute("content", this.tags.description);
    }
  }
}

export async function onRequest(context) {
  const { request, next, env } = context;
  const url = new URL(request.url);
  const path = url.pathname;
  
  // Extract ?article= ID from URL
  const articleId = url.searchParams.get("article");

  // Fetch the static built assets from Vite
  const response = await next();

  // Only rewrite HTML documents
  const contentType = response.headers.get("content-type") || "";
  if (!contentType.includes("text/html")) {
    return response;
  }

  // ==========================================
  // RULE D: The Absolute Fallback
  // ==========================================
  let currentTags = {
    title: "Super League - IIIT Kottayam",
    description: "Welcome to the Super League at IIIT Kottayam!",
    image: "https://pub-07c808f42c4640ceb3db8a0ef856e898.r2.dev/wsl.png"
  };

  // ==========================================
  // RULE A: Dynamic Newsletter Link (Supabase)
  // ==========================================
  if (articleId) {
    try {
      const supabaseResponse = await fetch(
        `${env.SUPABASE_URL}/rest/v1/newsletter?id=eq.${articleId}&select=image_url`,
        {
          headers: {
            "apikey": env.SUPABASE_ANON_KEY,
            "Authorization": `Bearer ${env.SUPABASE_ANON_KEY}`
          }
        }
      );

      if (supabaseResponse.ok) {
        const data = await supabaseResponse.json();
        if (data && data.length > 0 && data[0].image_url) {
          currentTags.title = "Newsletter | Super League";
          currentTags.image = data[0].image_url;
        }
      }
    } catch (err) {
      console.error("Supabase fetch failed:", err);
    }
  }
  // ==========================================
  // RULE B: The Fantasy Route
  // ==========================================
  else if (path === "/fantasy" || path === "/fantasy/") {
    currentTags.title = "FIFA Fantasy League | Super League";
    currentTags.image = "https://pub-07c808f42c4640ceb3db8a0ef856e898.r2.dev/World%20cup.png";
  }
  // ==========================================
  // RULE C: Automated Screenshots Mapping
  // ==========================================
  else if (["/matches", "/standings", "/clubs", "/statistics", "/legends", "/rules"].includes(path)) {
    const pageName = path.charAt(1).toUpperCase() + path.slice(2);
    currentTags.title = `${pageName} | Super League`;
    // Maps exactly to the filenames generated by your GitHub Action
    currentTags.image = `https://pub-07c808f42c4640ceb3db8a0ef856e898.r2.dev${path}.png`;
  }

  // Rewrite and send!
  return new HTMLRewriter()
    .on('meta', new MetaTagRewriter(currentTags))
    .transform(response);
}
